// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login/AdminLogin.tsx": () => import("../components/mockups/login/AdminLogin.tsx"),
  "./components/mockups/login/UserLogin.tsx": () => import("../components/mockups/login/UserLogin.tsx")
};
